# 本地开发环境

# Each TCP port is assigned a unique number ranging from 0 to 65535. 
# These ports are categorized into three ranges: 
# well-known ports (0-1023)
# registered ports (1024-49151)
# dynamic or private ports (49152-65535)

# SFTP config
sftp:
  # the connections applied for inbound and outbound
  connections:
    df:
      host: 192.168.1.31
      port: 22
      user: sftpusr
      privateKey: file:E:\code\.ssh\id_rsa
  # inbound config
  inbound:
    retry:
      maxAttempts: 4
      maxWaitTime: 300000
    connections:
      in:
        host: 192.168.1.31
        port: 22
        user: sftpusr
        privateKey: file:E:\code\.ssh\id_rsa
    rules:
      - id: 123456
        name: test-inbound
        schema: in
        remoteSource: /home/sftpusr/sftp-staging/tms/inbound
        remoteTemp: /home/sftpusr/sftp-staging/tms/inbound/temp
        remoteArchive: /home/sftpusr/sftp-staging/tms/inbound/archive
        archiveByDate: true
        pattern: "{spring:\\S+_TRANSACTION_[0-9]{8}_[0-9]+.json}"
        local: C:\Users\lenovo\Desktop\tmp\input
        retryMaxAttempts: 4
        retryMaxWaitTime: 3000
  # outbound config
  outbound:
    retry:
      maxAttempts: 4
      maxWaitTime: 300000
    connections:
      ot:
        host: 127.0.0.1
        port: 54663
        user: foo
        privateKey: classpath:/META-INF/keys/sftp_rsa
        privateKeyPassphrase: foo
      ot-unknown-host:
        host: 888.888.888.888
        port: 54663
        user: foo
        privateKey: classpath:/META-INF/keys/sftp_rsa
        privateKeyPassphrase: foo
      ot-unknown-port:
        host: 127.0.0.1
        port: 12345
        user: foo
        privateKey: classpath:/META-INF/keys/sftp_rsa
        privateKeyPassphrase: foo
