# 本地开发环境

# Each TCP port is assigned a unique number ranging from 0 to 65535. 
# These ports are categorized into three ranges: 
# well-known ports (0-1023)
# registered ports (1024-49151)
# dynamic or private ports (49152-65535)

# SFTP config
sftp:
  # the connections applied for inbound and outbound
  connections:
    df:
      host: 127.0.0.1
      port: 54661
      user: foo
      privateKey: classpath:/META-INF/keys/sftp_rsa
      privateKeyPassphrase: foo
  # inbound config
  inbound:
    retry:
      maxAttempts: 4
      maxWaitTime: 300000
    connections:
      in:
        host: 127.0.0.1
        port: 54662
        user: foo
        privateKey: classpath:/META-INF/keys/sftp_rsa
        privateKeyPassphrase: foo
    rules:
      - id: 123456
        name: test-inbound
        schema: in
        remoteSource: /path/to/source
        remoteTemp: /path/to/temp
        remoteArchive: /path/to/archive
        archiveByDate: true
        pattern: "*.txt"
        local: C:\Users\lenovo\Desktop\tmp\input
        retryMaxAttempts: 4
        retryMaxWaitTime: 3000
  # outbound config
  outbound:
    retry:
      maxAttempts: 4
      maxWaitTime: 300000
    connections:
      ot:
        host: 127.0.0.1
        port: 54663
        user: foo
        privateKey: classpath:/META-INF/keys/sftp_rsa
        privateKeyPassphrase: foo
      ot-unknown-host:
        host: 888.888.888.888
        port: 54663
        user: foo
        privateKey: classpath:/META-INF/keys/sftp_rsa
        privateKeyPassphrase: foo
      ot-unknown-port:
        host: 127.0.0.1
        port: 12345
        user: foo
        privateKey: classpath:/META-INF/keys/sftp_rsa
        privateKeyPassphrase: foo
